services:
  zebra-api:
    container_name: zebra-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
       - .env
    depends_on:
      - postgres-zebra-db
      - redis
    networks:
      - zebra-network

  postgres-zebra-db:
    container_name: postgres-zebra-db
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zebra
      POSTGRES_PASSWORD: zebra
      POSTGRES_DB: zebra
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - zebra-network

  pgadmin-zebra:
    container_name: pgadmin-zebra
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: zebra@zebra.com
      PGADMIN_DEFAULT_PASSWORD: zebra
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - zebra-network
    depends_on:
      - postgres-zebra-db

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - zebra-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - zebra-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - zebra-network
    depends_on:
      - prometheus

networks:
  zebra-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
  redis:
  grafana-data:
